name: reciclaria_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.14
  - pip
  - pip:
      # --- CV ---
      - onnxruntime==1.23.2
      - Pillow==11.1.0
      - numpy==2.3.5
      
      # --- RAG y Procesamiento de Lenguaje ---
      - langchain==1.1.3
      - langchain-chroma==1.1.0
      - langchain-ollama==1.0.1
      - chromadb==1.3.7
      - pypdf==6.4.1
      - python-dotenv==1.2.1
      
      # --- Utilidades adicionales ---
      - tqdm==4.67.1
      - requests==2.32.5