name: rag_estable
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - ld_impl_linux-64=2.44
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.11.14
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - acres==0.5.0
      - aiofiles==25.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.12.0
      - attrs==25.4.0
      - backoff==2.2.1
      - bcrypt==5.0.0
      - beautifulsoup4==4.14.3
      - bs4==0.0.2
      - build==1.3.0
      - cachetools==6.2.3
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - chromadb==1.3.7
      - ci-info==0.3.0
      - click==8.3.1
      - coloredlogs==15.0.1
      - configobj==5.0.9
      - configparser==7.2.0
      - dataclasses-json==0.6.7
      - distro==1.9.0
      - durationpy==0.10
      - etelemetry==0.3.1
      - filelock==3.20.0
      - flatbuffers==25.9.23
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - google-auth==2.43.0
      - googleapis-common-protos==1.72.0
      - greenlet==3.3.0
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httplib2==0.31.0
      - httptools==0.7.1
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - huggingface-hub==1.2.3
      - humanfriendly==10.0
      - idna==3.11
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - itsdangerous==2.2.0
      - jiter==0.12.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kubernetes==34.1.0
      - langchain==1.1.3
      - langchain-chroma==1.1.0
      - langchain-classic==1.0.0
      - langchain-community==0.4.1
      - langchain-core==1.2.0
      - langchain-ollama==1.0.1
      - langchain-openai==1.1.3
      - langchain-text-splitters==1.0.0
      - langgraph==1.0.5
      - langgraph-checkpoint==3.0.1
      - langgraph-prebuilt==1.0.5
      - langgraph-sdk==0.3.0
      - langsmith==0.4.59
      - looseversion==1.3.0
      - lxml==6.0.2
      - markdown-it-py==4.0.0
      - marshmallow==3.26.1
      - mdurl==0.1.2
      - mmh3==5.2.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - networkx==3.6.1
      - nibabel==5.3.3
      - nipype==1.10.0
      - numpy==2.3.5
      - oauthlib==3.3.1
      - ollama==0.6.1
      - onnxruntime==1.23.2
      - openai==2.11.0
      - opentelemetry-api==1.39.1
      - opentelemetry-exporter-otlp-proto-common==1.39.1
      - opentelemetry-exporter-otlp-proto-grpc==1.39.1
      - opentelemetry-proto==1.39.1
      - opentelemetry-sdk==1.39.1
      - opentelemetry-semantic-conventions==0.60b1
      - orjson==3.11.5
      - ormsgpack==1.12.0
      - overrides==7.7.0
      - pandas==2.3.3
      - pathlib==1.0.1
      - posthog==5.4.0
      - propcache==0.4.1
      - protobuf==6.33.2
      - prov==2.1.1
      - puremagic==1.30
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybase64==1.4.3
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pydot==4.0.1
      - pymupdf==1.26.7
      - pyparsing==3.2.5
      - pypdf==6.4.1
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyxnat==1.6.4
      - pyyaml==6.0.3
      - rdflib==7.5.0
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rich==14.2.0
      - rpds-py==0.30.0
      - rsa==4.9.1
      - scipy==1.16.3
      - shellingham==1.5.4
      - simplejson==3.20.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - sqlalchemy==2.0.45
      - starlette==0.50.0
      - sympy==1.14.0
      - tenacity==9.1.2
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - tqdm==4.67.1
      - traits==7.1.0
      - typer==0.20.0
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.3.0
      - uuid-utils==0.12.0
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - watchfiles==1.1.1
      - websocket-client==1.9.0
      - websockets==15.0.1
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
      - zstandard==0.25.0
prefix: /home/jaume/miniconda3/envs/rag_estable
